// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQqwKfw81a0Pd7YrA2_JcnOrBsuB2DcY',
    appId: '1:967077780131:web:3a907654affceb5fafbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    authDomain: 'notetestlol.firebaseapp.com',
    storageBucket: 'notetestlol.appspot.com',
    measurementId: 'G-0VMD3XKJ32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QgfBoZYkvGEPy7Opl0DVfgPfEYacpOA',
    appId: '1:967077780131:android:d81e6fba7662c2cfafbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    storageBucket: 'notetestlol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlCGCBFwqjNArHiJVQbeF-h3zfoDfZcU',
    appId: '1:967077780131:ios:bd04266bcd0d0af7afbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    storageBucket: 'notetestlol.appspot.com',
    iosClientId: '967077780131-3uv9i134ar5idq1or5rg86hqnfekgb0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.testnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlCGCBFwqjNArHiJVQbeF-h3zfoDfZcU',
    appId: '1:967077780131:ios:612bfc11f19f3b82afbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    storageBucket: 'notetestlol.appspot.com',
    iosClientId: '967077780131-ndkr7i5kfi7vn70aqois0t6tp9blbsp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testnote.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMQqwKfw81a0Pd7YrA2_JcnOrBsuB2DcY',
    appId: '1:967077780131:web:e312c2e27abf9471afbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    authDomain: 'notetestlol.firebaseapp.com',
    storageBucket: 'notetestlol.appspot.com',
    measurementId: 'G-PR35ZHHPD1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCMQqwKfw81a0Pd7YrA2_JcnOrBsuB2DcY',
    appId: '1:967077780131:web:f4929e687075e905afbd16',
    messagingSenderId: '967077780131',
    projectId: 'notetestlol',
    authDomain: 'notetestlol.firebaseapp.com',
    storageBucket: 'notetestlol.appspot.com',
    measurementId: 'G-LC1PDPRS3S',
  );
}
